# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e00820a4118eb23a3744c36a99b255ab22a3d94ba0714f99d70579882de04253e42da147edef5015200d18b1f7fc0a78d9c2f951c0e05549e3156b5c3f9f7a6

test:
  secret_key_base: 31e0ca006112fe0286e94719c86025733900d8adc0eb12b98add9459b4f6a358b5dfa1877199d468f43d40049d4fb3a0e987f207dc2f720b4b237cde1cf939ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
